theme: jekyll-theme-cayman
title: Gender Representation and Opinion Detection in the Media
description: We created a dashboard to measure the representation of women in the media for ReThink Media, an organization that strengthens movements through communications
