theme: jekyll-theme-minimal
title: Gender Representation and Opinion Detection in the Media
description: Capstone project building a dashboard to measure the representation of women in the media. Built for ReThink Media, an organization that strengthens movements through communications.
